"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

final_space = true
version = 2
pwd = "osc51"
shell_integration = true
patch_pwsh_bleed = true
disable_notice = true
auto_upgrade = false

[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = "path"
style = "plain"
foreground = "cyan"
template = "{{.Path}}"

[blocks.segments.properties]
style = "folder"

[[blocks]]
newline = true
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = "text"
style = "plain"
foreground = "magenta"
template = ">"

