"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$git_state\
$fill\
$cmd_duration\
$status\
$line_break\
$username\
"""

[directory]
format = '[$path](cyan) '

[git_branch]
format = '[$branch(:$remote_branch)](blue) '

[git_commit]
format = '[$hash](yellow)[$tag](purple) '
tag_disabled = false
tag_symbol = ' '

[git_status]
format = '$ahead_behind$stashed$conflicted$staged$deleted$renamed$modified$untracked'
ahead = '[↑${count}](green) '
behind = '[↓${count}](yellow) '
diverged = '[↓${behind_count}](yellow) [↑${ahead_count}](green) '
stashed = '[↙${count}](purple) '
conflicted = '[?${count}](red) '
staged = '[+${count}](green) '
deleted = '[-${count}](yellow) '
renamed = '[→${count}](yellow) '
modified = '[~${count}](yellow) '
untracked = '[*${count}](red) '

[git_state]
format = '[$state( $progress_current/$progress_total)](white) '
merge = 'merge'
rebase = 'rebase'
revert = 'revert'
cherry_pick = 'cherry-pick'
bisect = 'bisect'

[fill]
symbol = ' '

[cmd_duration]
format = '[$duration](purple) '
min_time = 5_000

[status]
format = '[$status](black) '
disabled = false

[character]
format = '$symbol '
success_symbol = '[●•](blue)'
error_symbol = '[●•](red)'

[username]
format = '[●•]($style) '
style_user = 'blue'
style_root = 'red'
show_always = true

