"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1_000
continuation_prompt = ' • '
format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$cmd_duration\
$status\
$line_break\
$character\
"""

[username]
format = '[⛊](yellow) '

[directory]
format = '[$path](cyan) '

[git_branch]
format = '[$branch(:$remote_branch)](blue) '

[git_commit]
format = '[$hash](yellow)[$tag](purple) '
tag_disabled = false
tag_symbol = ' '

[git_status]
format = '$ahead_behind$stashed$conflicted$staged$renamed$deleted$modified$untracked'
ahead = '[↑${count}](green) '
behind = '[↓${count}](yellow) '
diverged = '[↓${behind_count}](yellow) [↑${ahead_count}](green) '
stashed = '[←${count}](purple) '
conflicted = '[?${count}](red) '
staged = '[+${count}](green) '
renamed = '[→${count}](green) '
deleted = '[-${count}](red) ' # https://github.com/starship/starship/issues/3048
modified = '[~${count}](yellow) '
untracked = '[*${count}](red) '

[fill]
symbol = ' '

[cmd_duration]
format = '[$duration](purple) '
min_time = 5_000

[status]
format = '[$status](black) '
disabled = false

[character]
format = '$symbol '
success_symbol = '[●•](blue)'
error_symbol = '[●•](red)'

